<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Valve" Id="{530fbcc6-073c-4f99-a235-ea2b7e45a87d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Valve EXTENDS FB_Base IMPLEMENTS I_Valve
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="MoveToHome" Id="{a3b2d830-9e2d-4c42-9c66-dcf8ffc96541}">
      <Declaration><![CDATA[METHOD MoveToHome : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[Tc2_System.ADSLOGSTR(0, 'valve move to home', '');

MoveToHome := TRUE;]]></ST>
      </Implementation>
    </Method>
    <Method Name="MoveToWork" Id="{9d596b34-086c-4c11-b355-243d5fd015ff}">
      <Declaration><![CDATA[METHOD MoveToWork : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[Tc2_System.ADSLOGSTR(0, 'valve move to work', '');

MoveToWork := TRUE;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>