<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_BuildString" Id="{4bb7c327-72de-4bac-bd0a-0c4baff7eb29}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_BuildString : REFERENCE TO FB_StringBuilder
VAR_INPUT
	value : T_MaxString;
END_VAR
VAR
END_VAR
VAR_STAT
	builder : FB_StringBuilder;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[builder.Clear();

builder.Append(value);

F_BuildString REF= builder;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>