<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Axis" Id="{24a9cdac-e68f-40e5-8ce6-e0b3ae83894a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Axis EXTENDS FB_Base IMPLEMENTS I_Axis
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="InPosition" Id="{031a12bb-7b5c-4e2e-a15a-8d27a2e89b04}">
      <Declaration><![CDATA[METHOD InPosition : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="MoveAbsolute" Id="{1175759c-5dea-4004-a9bd-113763a78787}">
      <Declaration><![CDATA[METHOD MoveAbsolute : BOOL
VAR_INPUT
	target : REAL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>